### ISSUE TITLE
Create dataframe of out-references

### ISSUE THREAD

**Issue by samunico** [samunico/Apart#4]
This dataframe should include:
- relevant tokens within same window (10 tokens in both directions)
- addressee
- sentiment score
- speaker
- date
- speech-ID

**Comment by jnareal** [comment]
Just to be sure, then, this in line with the idea of having each 'window' as one row in our final dataframe, right?

**Comment by samunico** [comment]
@jnareal : focus on windows
@samunico : focus on addressee
